# Generated by Django 4.0.6 on 2022-07-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_variation_cartitem_variations'),
        ('store', '0004_alter_variation_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variety',
        ),
    ]
