# Generated by Django 4.0.6 on 2022-07-30 17:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variety_managers_remove_variety_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variety',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
