# Generated by Django 4.0.6 on 2022-08-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_address_email_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
