# Generated by Django 4.0.6 on 2022-07-26 06:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('obejct', django.db.models.manager.Manager()),
            ],
        ),
    ]
